// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"rumahdermawan/backedn-rdi/app"
	"rumahdermawan/backedn-rdi/controller/activity"
	period3 "rumahdermawan/backedn-rdi/controller/period"
	user3 "rumahdermawan/backedn-rdi/controller/user"
	"rumahdermawan/backedn-rdi/repository/activities"
	"rumahdermawan/backedn-rdi/repository/period"
	"rumahdermawan/backedn-rdi/repository/user"
	activities2 "rumahdermawan/backedn-rdi/service/activities"
	period2 "rumahdermawan/backedn-rdi/service/period"
	user2 "rumahdermawan/backedn-rdi/service/user"
)

// Injectors from injector.go:

func InitializedServer() *gin.Engine {
	db := app.NewDb()
	userRepositoryImpl := user.NewUserRepository(db)
	validate := validator.New()
	userServiceImpl := user2.NewUserService(userRepositoryImpl, validate)
	userTokenImpl := user3.NewServiceUserToken()
	userControllerImpl := user3.NewUserController(userServiceImpl, userTokenImpl)
	periodRepositoryImpl := period.NewPeriodRepository(db)
	periodServiceImpl := period2.NewPeriodService(periodRepositoryImpl, validate)
	periodControllerImpl := period3.NewPeriodController(periodServiceImpl)
	activityRepositoryImpl := activities.NewActivityRepository(db)
	activityServiceImpl := activities2.NewActivityService(activityRepositoryImpl, periodRepositoryImpl, validate)
	activityControllerImpl := activity.NewActivityController(activityServiceImpl)
	engine := app.NewRouter(userControllerImpl, periodControllerImpl, activityControllerImpl, userTokenImpl, userServiceImpl)
	return engine
}

// injector.go:

var userSet = wire.NewSet(user.NewUserRepository, wire.Bind(new(user.UserRepository), new(*user.UserRepositoryImpl)), user2.NewUserService, wire.Bind(new(user2.UserService), new(*user2.UserServiceImpl)), user3.NewServiceUserToken, wire.Bind(new(user3.UserToken), new(*user3.UserTokenImpl)), user3.NewUserController, wire.Bind(new(user3.UserController), new(*user3.UserControllerImpl)))

var periodSet = wire.NewSet(period.NewPeriodRepository, wire.Bind(new(period.PeriodRepository), new(*period.PeriodRepositoryImpl)), period2.NewPeriodService, wire.Bind(new(period2.PeriodService), new(*period2.PeriodServiceImpl)), period3.NewPeriodController, wire.Bind(new(period3.PeriodController), new(*period3.PeriodControllerImpl)))

var activitySet = wire.NewSet(activities.NewActivityRepository, wire.Bind(new(activities.ActivitiyRepository), new(*activities.ActivityRepositoryImpl)), activities2.NewActivityService, wire.Bind(new(activities2.ActivityService), new(*activities2.ActivityServiceImpl)), activity.NewActivityController, wire.Bind(new(activity.ActivityController), new(*activity.ActivityControllerImpl)))
